refresh-project/refresh-project.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace refresh_project.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

refresh-project/refresh-project.Web/Controllers/PendaftarController.cs
using DocumentFormat.OpenXml.Office2010.Excel;
using refresh_project.DataModel;
using refresh_project.Repository;
using refresh_project.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace refresh_project.Web.Controllers
{
    public class PendaftarController : Controller
    {
        // GET: Pendaftar
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            ViewBag.jeniskelamin = PendaftarRepo.genderList();
            List<tb_form_covid> list = PendaftarRepo.GetAll();
            return PartialView("_List", list);
        }

        public ActionResult Details(long id)
        {
            ViewBag.jeniskelamin = PendaftarRepo.genderName(id);
            return PartialView("_Details", PendaftarRepo.ById(id));
        }

        public ActionResult Edit(long id)
        {
            return PartialView("_Edit", PendaftarRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Edit(PendaftarViewModel model)
        {
            try
            {
                ResponseResult result = new ResponseResult();
                PendaftarRepo.alert = string.Empty;
                
                //VALIDASI EMAIL
                String[] val_email = model.Email.Split('@');
                if (val_email.Length == 1)
                {
                    PendaftarRepo.alert = "Format email salah. ";
                }

                //VALIDASI NO.HP
                char[] hp = model.No_Telp.ToCharArray();                
                for (int i = 0; i < 2; i++)
                {
                    if (hp[0] != '0' && hp[1] != '8')
                    {
                        PendaftarRepo.alert = "Format email salah. ";
                        break;
                    }
                }

                using (var db = new refresh_projectContext())
                {
                    var data = db.tb_form_covid.ToList();
                    //VALIDASI EMAIL DENGAN DATABASE
                    if (data.Any(o => o.Email == model.Email && o.Id != model.Id))
                    {
                        PendaftarRepo.alert = "Email sudah pernah digunakan.";
                    }
                    //VALIDASI NO. HP DENGAN DATABASE
                    if (data.Any(o => o.No_Telp == model.No_Telp && o.Id != model.Id))
                    {
                        PendaftarRepo.alert = "No. HP sudah pernah digunakan.";
                    }
                    //VALIDASI IDENTITAS DENGAN DATABASE
                    if (data.Any(o => o.NPM == model.NPM && o.Id != model.Id))
                    {
                        PendaftarRepo.alert = "NPM/NIS sudah pernah digunakan.";
                    }
                }

                if (string.IsNullOrEmpty(PendaftarRepo.alert))
                {
                    return Json(
                    new
                    {
                        success = PendaftarRepo.Update(model),
                        message = result.Message,
                    },
                    JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(
                    new
                    {
                        success = false,
                        message = PendaftarRepo.alert,
                    },
                    JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(
                    new
                    {
                        success = false,
                        message = ex.Message,
                    },
                    JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Create()
        {
            return PartialView("_Create");
        }

    }
}

refresh-project/refresh-project.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

refresh-project/refresh-project.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

refresh-project/refresh-project.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

refresh-project/refresh-project.Web/Views/Pendaftar/Index.cshtml
<div class="body body-content">
    <div class="body-header" style="width: inherit; padding-left: 15px; margin-right:15px; color:#30336A; border-color:#30336A">
        <div class="body-applicant">

        </div>
    </div>
</div>

@*MODAL DETAIL*@
<div id="modal-all" class="modal fade" tabindex="-1" role="dialog" style="position:center">
    <div class="modal-dialog" role="document" style="max-width:600px">
        <div class="modal-content">
            <div class="modal-header" style="background-color:#30336A; color:white">
                <h4 class="modal-title" id="modalTitle"></h4>        @*<---TITTLE NYA NIH*@
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color:white"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@*MODAL EDIT*@
<div id="modal-edit" class="modal fade" tabindex="-1" role="dialog" style="position:center">
    <div class="modal-dialog" role="document" style="max-width:1000px">
        <div class="modal-content">
            <div class="modal-header" style="background-color:#30336A; color:white">
                <h4 class="modal-title" id="modalTitle"></h4>        @*<---TITTLE NYA NIH*@
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color:white"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section scripts{
    <script type="text/javascript">
    $(document).ready(function () {
        GetList()
    })

        //LIST
        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "Pendaftar")',
                type: 'get',
                success: function (result) {
                    $(".body-applicant").html(result);
                }
            });
        }

        //CREATE
        $("#btn-create").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "Applicant")',
                type: 'get',
                success: function (result) {
                    $(".body-applicant").html(result);
                }
            });
        })

        //DETAILS
        function DetailsById(id) {
            $.ajax({
                url: '@Url.Action("Details", "Pendaftar")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal-all").modal("show");
                    $("#modalTitle").text("Detail Pendaftar");
                }
            });
        }

        //EDIT
        function EditById(id) {
            $.ajax({
                url: '@Url.Action("Edit", "Pendaftar")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal-edit").modal("show");
                    $("#modalTitle").text("Edit Data Pendaftar");
                }
            });
        }

        //DELETE
        function DeleteById(id) {
            $.ajax({
                url: '@Url.Action("Delete", "Sales")',
                type: 'get',
                data: { id: id },
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal-all").modal("show");
                    $("#modalTitle").text("Delete Data");
                }
            });
        }

    </script>
}

refresh-project/refresh-project.Web/Views/Pendaftar/_Details.cshtml
@model refresh_project.ViewModel.PendaftarViewModel

<table class="table table-striped" style="color:#000066">
    @*<caption class="row">
            <h3 style="margin-top:0px">
                <span id="judul" style="font:bold; color:#000066; border-bottom:2px; margin-left:15px"></span>
                <button class="glyphicon glyphicon-edit" style="background-color: transparent; color:#000066; border-color:transparent" id="editBtn" data-id="@item.id" onclick="Edit(@item.id)" type="button"></button>
            </h3>
            <div class="col-xs-12" style="border-color:#000066">
                <hr-edit></hr-edit>
            </div>
        </caption>*@
    <tr style="border-top: 4px #000066">
        <th>Nama - Umur</th>
        <th>: @Html.DisplayFor(model => model.Nama) - @Html.DisplayFor(model => model.Umur)</th>
    </tr>
    <tr>
        <th>NPM/NIS</th>
        <th>: @Html.DisplayFor(model => model.NPM)</th>
    </tr>
    <tr>
        <th>Kontak</th>
        <th>: @Html.DisplayFor(model => model.No_Telp) / @Html.DisplayFor(model => model.Email)</th>
    </tr>
    <tr>
        <th>Alamat</th>
        <th>: @Html.DisplayFor(model => model.Alamat_Sekarang)</th>
    </tr>
    <tr>
        <th>Alamat Asal</th>
        <th>: @Html.DisplayFor(model => model.Alamat_Asal)</th>
    </tr>
    <tr>
        <th>Lokasi</th>
        <th>: @Html.DisplayFor(model => model.Lokasi)</th>
    </tr>
    <tr>
        <th>Jenis Kelamin</th>
        <th>: @ViewBag.jeniskelamin</th>
    </tr>
</table>

refresh-project/refresh-project.Web/Views/Pendaftar/_Edit.cshtml
@model refresh_project.ViewModel.PendaftarViewModel

@using (Html.BeginForm("Edit", "Pendaftar", FormMethod.Post, new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="container" style="color: #30336A; border-bottom-color: #30336A; font-size: 14px; padding:0px 0px 0px 0px">
            @*NAMA-----2-----*@
            <div class="row" style="width:1000px">
                <div class="col">
                    <div class="col-xs-6">
                        <label class="control-label FormLabel" style="text-align:left">Nama *</label>
                        <div class="FormEdit">
                            @Html.EditorFor(model => model.Nama, new { htmlAttributes = new { @class = "form-control input-lg FormText" } })
                            @Html.ValidationMessageFor(model => model.Nama, "", new { @class = "FormAlert" })
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="col-xs-6">
                        <label class="control-label FormLabel" style="text-align:left">Email Address *</label>
                        <div class="FormEdit">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control input-lg FormText" , @type = "email"} })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "FormAlert" })
                        </div>
                    </div>
                </div>
            </div>
            @*----------------------------------------------------------------------------------------------------------------------------------------------------------*@
            <div class="row" style="width:1000px">
                <div class="col">
                    <div class="col-xs-3">
                        <label class="control-label FormLabel" style="text-align:left">NPM/NIS *</label>
                        <div class="FormEdit">
                            @Html.EditorFor(model => model.NPM, new { htmlAttributes = new { @class = "form-control input-lg FormText", @type = "number" } })
                            @Html.ValidationMessageFor(model => model.NPM, "", new { @class = "FormAlert" })
                        </div>
                    </div>
                    <div class="col-xs-3">
                        <label class="control-label FormLabel" style="text-align:left">Umur *</label>
                        <div class="FormEdit">
                            @Html.EditorFor(model => model.Umur, new { htmlAttributes = new { @class = "form-control input-lg FormText" } })
                            @Html.ValidationMessageFor(model => model.Umur, "", new { @class = "FormAlert" })
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="col-xs-6">
                        <label class="control-label FormLabel" style="text-align:left">No. Telepon *</label>
                        <div class="FormEdit">
                            @Html.EditorFor(model => model.No_Telp, new { htmlAttributes = new { @class = "form-control input-lg FormText", @type = "number" } })
                            @Html.ValidationMessageFor(model => model.No_Telp, "", new { @class = "FormAlert" })
                        </div>
                    </div>
                </div>
            </div>
            @*----------------------------------------------------------------------------------------------------------------------------------------------------------*@
            <div class="row" style="width:1000px">
                <div class="col">
                    <div class="col-xs-6">
                        <label class="control-label FormLabel" style="text-align:left">Alamat Asal *</label>
                        <div class="FormEdit">
                            @Html.EditorFor(model => model.Alamat_Asal, new { htmlAttributes = new { @class = "form-control input-lg FormText" } })
                            @Html.ValidationMessageFor(model => model.Alamat_Asal, "", new { @class = "FormAlert" })
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="col-xs-6">
                        <label class="control-label FormLabel" style="text-align:left">Alamat Saat Ini *</label>
                        <div class="FormEdit">
                            @Html.EditorFor(model => model.Alamat_Sekarang, new { htmlAttributes = new { @class = "form-control input-lg FormText" } })
                            @Html.ValidationMessageFor(model => model.Alamat_Sekarang, "", new { @class = "FormAlert" })
                        </div>
                    </div>
                </div>
            </div>
            @*----------------------------------------------------------------------------------------------------------------------------------------------------------*@
            <div class="row" style="width:1000px">
                <div class="col">
                    <div class="col-xs-6">
                        <label class="control-label FormLabel" style="text-align:left">Jenis Kelamin *</label>
                        <div class="FormEdit">
                            @Html.EditorFor(model => model.Jenis_Kelamin, new { htmlAttributes = new { @class = "form-control input-lg FormText" } })
                            @Html.ValidationMessageFor(model => model.Jenis_Kelamin, "", new { @class = "FormAlert" })
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="col-xs-6">
                        <label class="control-label FormLabel" style="text-align:left">Lokasi Saat Ini *</label>
                        <div class="FormEdit">
                            @Html.EditorFor(model => model.Lokasi, new { htmlAttributes = new { @class = "form-control input-lg FormText" } })
                            @Html.ValidationMessageFor(model => model.Lokasi, "", new { @class = "FormAlert" })
                        </div>
                    </div>
                </div>
            </div>
        </div>        
    </div>

    <div class="modal-footer" style="margin-right: 25px">
        <input type="button" value="Batal" title="Cancel" class="btn" style="background-color: #FF6600; color:white" data-dismiss="modal" />
        <input type="submit" value="Simpan" title="Save" class="btn" style="background-color: #000066; color:white" />
    </div>
}


@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#form-edit").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert('Save successfully!');
                    $("#modal-edit").modal("hide");
                    GetList()
                }
                else {
                    alert('Error: ' + result.message);
                }
            }
        })
        return false;
    })
</script>

refresh-project/refresh-project.Web/Views/Pendaftar/_List.cshtml
@model IEnumerable<refresh_project.DataModel.tb_form_covid>


<h2 style="position:center; color:#30336A" align="center"><strong>List Pendaftar</strong></h2>
<table class="table table-striped">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Nama)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            Jenis Kelamin
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lokasi)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <button type="button" class="btn btn-default btn-lg" data-id="@item.Id" onclick="DetailsById(@item.Id)" style="background-color:white">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nama)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @ViewBag.jeniskelamin
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lokasi)
            </td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" style="color:white; background-color: #E43031">
                        More
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="#" data-id="@item.Id" onclick="DetailsById(@item.Id)">Details</a></li>
                        <li><a href="#" data-id="@item.Id" onclick="EditById(@item.Id)">Edit</a></li>
                        <li><a href="#" data-id="@item.Id" onclick="DeleteById(@item.Id)">Delete</a></li>
                    </ul>
                </div>
            </td>
        </tr>
    }

</table>